-- EMPLOYEES 테이블에서 EMPLOYEE_ID가 101인 정보를 조회.
SELECT *
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 101
;

-- EMPLOYEES 테이블에서 FIRST_NAME이 "Neena"인 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME = 'Neena'
;

-- EMPLOYEES 테이블에서 SALARY의 값이 6000 보다 큰 정보를 조회.
SELECT *
  FROM EMPLOYEES
 WHERE SALARY > 6000
;

-- EMPLOYEES 테이블에서 COMMISSION_PCT(인센티브)를 0.2보다 크거나 같은 정보를 SALARY로 내림차순해서 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE COMMISSION_PCT >= 0.2
 ORDER BY SALARY DESC
;
-- 실무에서는 * 는 잘쓰이지 않는다. 전부가져오더라도 모든 컬럼을 쓸 가능성이 있다.
-- EMPLOYEE_ID, FIRST_NAME, EMAIL, SALARY, COMMISSION_PCT만조회
SELECT EMPLOYEE_ID, FIRST_NAME, EMAIL, SALARY, COMMISSION_PCT
  FROM EMPLOYEES
 WHERE COMMISSION_PCT >= 0.2
 ORDER BY SALARY DESC
;

-- DEPARTMENTS(부서정보) 테이블에서 LOCATION_ID(지역번호)가 1700인 부서의
-- DEPARTMENT_ID(부서번호), DEPARTMENT_NAME(부서명), LOCATION_ID(지역번호)를
-- DEPARTMENT_NAME으로 내림차순 정렬해서 조회.
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
  FROM DEPARTMENTS
 WHERE LOCATION_ID = 1700
 ORDER BY DEPARTMENT_NAME DESC 
;

-- BETWEEN A AND B
-- DEPARTMENTS 테이블에서 LOCATION_ID가 1500부터 2000 사이에 있는 모든 정보를 조회.
SELECT *
  FROM DEPARTMENTS
 WHERE LOCATION_ID BETWEEN 1500 AND 2000
;

-- IS NULL, IS NOT NULL
-- DEPARTMENTS 테이블에서 MANAGER_ID (부서장 사원의 번호)가 없는 것만 조회.
SELECT *
  FROM DEPARTMENTS
 WHERE MANAGER_ID IS NULL -- IS NOT NULL 있는 것만 조회 
;

-- IN
-- EMPLOYEES 테이블에서 DEPARTMENT_ID(근무중인 부서번호)가 90이거나 30이거나 60이거나 100인 모든 정보를 조회.
SELECT *
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (90, 30, 60, 100) -- IN에 넣을 수 있는 비교값은 1000개 까지만 사용.
;

-- EMPLOYEES 테이블에서 JOB_ID(직무아이디)가 IT_PROG 이거나 AD_VP 이거나 FI_ACCOUNT인
-- EMPLOYEE_ID, JOB_ID, SALARY를 조회.
SELECT EMPLOYEE_ID, JOB_ID, SALARY
  FROM EMPLOYEES
 WHERE JOB_ID IN ('IT_PROG', 'AD_VP', 'FI_ACCOUNT')
;

-- EMPLOYEES 테이블에서 JOB_ID(직무아이디)가 IT_PROG 이거나 AD_VP 이거나 FI_ACCOUNT가 아닌
-- EMPLOYEE_ID, JOB_ID, SALARY를 조회.
SELECT EMPLOYEE_ID
	 , JOB_ID
	 , SALARY
  FROM EMPLOYEES
 WHERE JOB_ID NOT IN ('IT_PROG', 'AD_VP', 'FI_ACCOUNT')
;

-- LIKE (자리수 체크) - 문자열검색만 가능
-- WILD CARD
-- 		"_"  : 아무글자 하나.
-- 		"%"  : 포함되어 있음.
-- 		"A%" : A로 시작하는 것
-- 		"%A" : A로 끝나는 것
-- 		"%A%": A가 포함되어 있는것
-- EMPLOYEES 테이블에서 FIRST_NAME이 5글자인 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '_____'
;

-- EMPLOYEES 테이블에서 FIRST_NAME이 6글자인 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '______'
;

-- EMPLOYEES 테이블에서 FIRST_NAME이 5글자가 아닌 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME NOT LIKE '_____'
;

-- EMPLOYEES 테이블에서 EMAIL이 S로 시작하는 모든 정보를 조회.
SELECT *
  FROM EMPLOYEES
 WHERE EMAIL LIKE 'S%'
;

-- EMPLOYEES 테이블에서 EMAIL이 S로 시작하지 않는 모든 정보를 조회.
SELECT *
  FROM EMPLOYEES
 WHERE EMAIL NOT LIKE 'S%'
;

-- EMPLOYEES 테이블에서 EMAIL이 'T'로 끝나는 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE EMAIL LIKE '%T'
;
-- EMPLOYEES 테이블에서 EMAIL이 'T'로 끝나지 않는 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE EMAIL NOT LIKE '%T'
;
-- EMPLOYEES 테이블에서 EMAIL이 'W'가 포함된 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE EMAIL LIKE '%W%'
;
-- EMPLOYEES 테이블에서 EMAIL이 'W'로 포함되지 않는 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE EMAIL NOT LIKE '%W%'
;

-- EMPLOYEES 테이블에서 PHONE_NUMBER가 "2" 로 끝나고
-- SALARY가 5000 이상이며
-- JOB_ID 가 "SA_REP" 인 모든 정보를 조회한다.
SELECT *
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '%2'
   AND SALARY >= 5000
   AND JOB_ID = 'SA_REP'
;
 
-- EMPLOYEES 테이블에서 FIRST_NAME 이 6자리이고
-- JOB_ID 가 "AD_PRES" 이거나, "IT_PROG"인 모든 정보를 조회한다.
-- AND OR 이 같이 쓰이면 반드시 검증이 필요하다.
SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '______'
   AND (JOB_ID = 'AD_PRES' 
    OR JOB_ID = 'IT_PROG')
;

SELECT *
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '______'
   AND JOB_ID IN ('AD_PRES', 'IT_PROG')
;

-- EMPLOYEES 테이블에서 MANAGER_ID 가 NULL이 아니고
-- COMMISSION_PCT 는 NULL이고
-- EMPLOYEE_ID 는 200 미만이면서
-- EMAIL이 "S" 혹은 "D"로 시작하는 모든 정보를 조회
SELECT *
  FROM EMPLOYEES
 WHERE MANAGER_ID IS NOT NULL 
   AND COMMISSION_PCT IS NULL
   AND EMPLOYEE_ID < 200
   AND (EMAIL LIKE 'S%'
    OR EMAIL LIKE 'D%')
;

-- 복사해가려고..ㅎ
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY
     , COMMISSION_PCT
     , MANAGER_ID
     , DEPARTMENT_ID
  FROM EMPLOYEES
;